# Generated by Django 5.0.2 on 2024-11-15 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UsuariosApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='real_password',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
